from Bio import SeqIO
import pandas as pd
import datetime
import ete3


metadf = pd.read_csv('../metadata/nov23update_250vir_SC2like_RacCSB20_meta_phylogeo.tsv', sep='\t')

allnrrs = 32

print(metadf)
taxanum = len(metadf)
pref = "R637"


chainlen = 1000000000
logevery = 100000
outnam = "raccsb20637_phylo_8"

def date2num(date_str):
    if len(date_str) == 10:
        # Try to parse the date in "YYYY-MM-DD" format
        date_obj = datetime.datetime.strptime(date_str, '%Y-%m-%d')
    elif len(date_str) == 7:
        # Try to parse the date in "YYYY-MM" format (day absent)
        date_obj = datetime.datetime.strptime(date_str, '%Y-%m')
    else:
        # Try to parse the date in "YYYY" format (day absent)
        date_obj = datetime.datetime.strptime(date_str, '%Y')
                
    # Calculate the fractional part of the year
    year_start = datetime.datetime(date_obj.year, 1, 1)
    year_end = datetime.datetime(date_obj.year + 1, 1, 1)
    year_elapsed = (date_obj - year_start).total_seconds()
    year_duration = (year_end - year_start).total_seconds()
    fraction = year_elapsed / year_duration

    # Combine the whole year and the fractional part
    decimal_year = date_obj.year + fraction
    return decimal_year



header = """
<?xml version="1.0" standalone="yes"?>

<!-- Generated by BEAUTi v1.10.4 Prerelease #bc6cbd9                         -->
<!--       by Alexei J. Drummond, Andrew Rambaut and Marc A. Suchard         -->
<!--       Department of Computer Science, University of Auckland and        -->
<!--       Institute of Evolutionary Biology, University of Edinburgh        -->
<!--       David Geffen School of Medicine, University of California, Los Angeles-->
<!--       http://beast.community/                                           -->
<beast version="1.10.4">


""".strip()



taxa = """
	<!-- The list of taxa to be analysed (can also include dates/ages).          -->
	<!-- ntaxa=%i                                                                -->
	<taxa id="taxa">
    """%(taxanum)

for i in metadf.index:
    taxid = metadf.loc[i,'name']
    dat = metadf.loc[i, 'date']
    lat = metadf.loc[i, 'latitude']
    long = metadf.loc[i, 'longitude']
    
    numdat = date2num(dat)
    datuncert = ""
    if len(dat) == 7:
        datuncert = " uncertainty=\"0.08333333333333333\""
    elif len(dat) == 4:
        datuncert = " uncertainty=\"1.0\""
        
        
    taxa = taxa + """    <taxon id="%s">
			<date value="%f" direction="forwards" units="years"%s/>
			<attr name="lat">
				%f
			</attr>
			<attr name="long">
				%f
			</attr>
			<attr name="loc">
				%f %f
			</attr>
		</taxon>
    """%(taxid, numdat, datuncert, lat, long, lat, long)
    
taxa = taxa.strip() + """
	</taxa>
    """


#add custom internal node taxa

taxa = taxa + """
	<taxa id="R637_RacCS203">
		<taxon idref="RacCS20637"/>
		<taxon idref="MW251308.1"/>
	</taxa>
	<taxa id="R637_BANAL103">
		<taxon idref="RacCS20637"/>
		<taxon idref="MZ937001.1"/>
	</taxa>
	<taxa id="R637_RaTG13">
		<taxon idref="RacCS20637"/>
		<taxon idref="MN996532.2"/>
	</taxa>
	<taxa id="R637_RpYN06">
		<taxon idref="RacCS20637"/>
		<taxon idref="MZ081381.1"/>
	</taxa>
	<taxa id="R637_Ra22QT77">
		<taxon idref="RacCS20637"/>
		<taxon idref="OR233324.1"/>
	</taxa>
	<taxa id="R637_BANAL52">
		<taxon idref="RacCS20637"/>
		<taxon idref="MZ937000.1"/>
	</taxa>
    """


alns = ""
pats = ""
startt = ""
tmod = ""
tmrca = ""
#custom taxa
tmrca_custtaxa = ""
tlen = ""
skygridpopt = ""
sitemod = ""
treedatl = ""
compparams = ""
distlparams = ""
diffbr = ""
diffdistlparams = ""
traitdatl = ""
vartraits = ""
spatialpr_rt = ""
spatialpr_var = ""
scaleop = ""
subtslide = ""
hammcop = ""
gibbsop = ""
geoop = ""
vargeoop = ""
flatgeo_pr = ""
flatgeo_var = ""
disc_br = ""
tree_like = ""
trait_like = ""

logpar = ""
logtmrca = ""
logtreelen = ""

logconj = ""
logratestat = "" 
logtreedat = ""
logtraitdat = ""
logdisc_br = ""

logwrite = ""


# for i in range(len(alnfs)):
for i in range(allnrrs):
    
    # nrrnum = [x for x in alnfs[i].split('_') if 'reg' in x][0][3:]
    nrrnum = str(i+1)
    
    # alnf = alnfs[i]    
    alnf = 'starting_trees/nov23update_250vir_SC2like_RacCSB20_phylogeo_NRR%s.linsi.fas'%nrrnum
    
    
    pats = pats + """	<!-- The unique patterns from 1 to end                                       -->
	<!-- npatterns=XXXX                                                           -->
	<patterns id="%s_NRR%s.patterns" from="1" strip="false">
		<alignment idref="alignment%i"/>
	</patterns>
    
"""%(pref, nrrnum, i+1)   
    
    t = ete3.Tree('starting_trees/nov23update_250vir_SC2like_RacCSB20_phylogeo_NRR%s.linsi.fas.treefile'%nrrnum)
    midR = t.get_midpoint_outgroup()
    t.set_outgroup(midR)
    
    startt = startt + """
	<newick id="%s_NRR%s.startingTree" usingHeights="false" usingDates="true">
		%s
	</newick>
"""%(pref, nrrnum, t.write())
# """%(pref, nrrnum, customtrees[i])
    
    
    tmod = tmod + """
	<treeModel id="%s_NRR%s.treeModel">
		<coalescentTree idref="%s_NRR%s.startingTree" />
		<rootHeight>
			<parameter id="%s_NRR%s.treeModel.rootHeight" />
		</rootHeight>
		<nodeHeights internalNodes="true">
			<parameter id="%s_NRR%s.treeModel.internalNodeHeights" />
		</nodeHeights>
		<nodeHeights internalNodes="true" rootNode="true">
			<parameter id="%s_NRR%s.treeModel.allInternalNodeHeights" />
		</nodeHeights>
		<nodeTraits rootNode="false" internalNodes="false" leafNodes="true" traitDimension="2" name="loc">
			<parameter id="%s_NRR%s.leafTraits" />
		</nodeTraits>
	</treeModel>"""%(pref, nrrnum, pref, nrrnum, pref, nrrnum, pref, nrrnum, pref, nrrnum, pref, nrrnum)
    
    tmrca = tmrca + """
	<tmrcaStatistic id="%s_NRR%s.age(root)" absolute="true">
		<treeModel idref="%s_NRR%s.treeModel" />
	</tmrcaStatistic>"""%(pref, nrrnum,pref, nrrnum)

    tmrca_custtaxa = tmrca_custtaxa + """
	<tmrcaStatistic id="%s_NRR%s.age(R637_RacCS203)" absolute="true" includeStem="false">
		<mrca>
			<taxa idref="R637_RacCS203"/>
		</mrca>
		<treeModel idref="%s_NRR%s.treeModel"/>
	</tmrcaStatistic>
	<tmrcaStatistic id="%s_NRR%s.age(R637_BANAL103)" absolute="true" includeStem="false">
		<mrca>
			<taxa idref="R637_BANAL103"/>
		</mrca>
		<treeModel idref="%s_NRR%s.treeModel"/>
	</tmrcaStatistic>
	<tmrcaStatistic id="%s_NRR%s.age(R637_RaTG13)" absolute="true" includeStem="false">
		<mrca>
			<taxa idref="R637_RaTG13"/>
		</mrca>
		<treeModel idref="%s_NRR%s.treeModel"/>
	</tmrcaStatistic>
	<tmrcaStatistic id="%s_NRR%s.age(R637_RpYN06)" absolute="true" includeStem="false">
		<mrca>
			<taxa idref="R637_RpYN06"/>
		</mrca>
		<treeModel idref="%s_NRR%s.treeModel"/>
	</tmrcaStatistic>
	<tmrcaStatistic id="%s_NRR%s.age(R637_Ra22QT77)" absolute="true" includeStem="false">
		<mrca>
			<taxa idref="R637_Ra22QT77"/>
		</mrca>
		<treeModel idref="%s_NRR%s.treeModel"/>
	</tmrcaStatistic>
	<tmrcaStatistic id="%s_NRR%s.age(R637_BANAL52)" absolute="true" includeStem="false">
		<mrca>
			<taxa idref="R637_BANAL52"/>
		</mrca>
		<treeModel idref="%s_NRR%s.treeModel"/>
	</tmrcaStatistic>"""%(pref, nrrnum, pref, nrrnum, pref, nrrnum, pref, nrrnum,
                        pref, nrrnum, pref, nrrnum, pref, nrrnum, pref, nrrnum,
                        pref, nrrnum, pref, nrrnum, pref, nrrnum, pref, nrrnum)

    
    tlen = tlen + """
	<treeLengthStatistic id="%s_NRR%s.treeLength">
		<treeModel idref="%s_NRR%s.treeModel" />
	</treeLengthStatistic>"""%(pref, nrrnum, pref, nrrnum)
    
    skygridpopt = skygridpopt + """
			<treeModel idref="%s_NRR%s.treeModel" />"""%(pref, nrrnum)
    
    
    sitemod = sitemod + """
	<!-- site model                                                              -->
	<siteModel id="%s_NRR%s.siteModel">
		<substitutionModel>
			<HKYModel idref="hky"/>
		</substitutionModel>
		<relativeRate weight="%i">
			<parameter id="%s_NRR%s.nu" value="%.8f" lower="0.0" />
		</relativeRate>
		<gammaShape gammaCategories="4">
			<parameter id="%s_NRR%s.alpha" value="0.5" lower="0.0" />
		</gammaShape>
	</siteModel>
    """%(pref, nrrnum, allnrrs, pref, nrrnum, 1/allnrrs, pref, nrrnum)
    # """%(pref, nrrnum, len(alnfs), pref, nrrnum, 1/len(alnfs), pref, nrrnum)
    
    
    treedatl = treedatl + """\t<treeDataLikelihood id="%s_NRR%s.treeLikelihood" useAmbiguities="false">
		<partition>
			<patterns idref="%s_NRR%s.patterns" />
			<siteModel idref="%s_NRR%s.siteModel" />
		</partition>
		<treeModel idref="%s_NRR%s.treeModel" />
		<strictClockBranchRates idref="sarbeco.branchRates" />
	</treeDataLikelihood>
"""%(pref, nrrnum, pref, nrrnum, pref, nrrnum, pref, nrrnum)
    
    
    compparams = compparams + """
		<parameter idref="%s_NRR%s.nu" />"""%(pref, nrrnum)    
    
    
    distlparams = distlparams + """
		<parameter idref="%s_NRR%s.alpha" />"""%(pref, nrrnum)    
    
    diffbr = diffbr+ """
	<arbitraryBranchRates id="%s_NRR%s.branchRatesDiffusion" centerAtOne="false" randomizeRates="true">
		<treeModel idref="%s_NRR%s.treeModel" />
		<rates>
			<parameter id="%s_NRR%s.branchRatesDiffusion.rates" />
		</rates>
	</arbitraryBranchRates>
	<rateStatistic id="%s_NRR%s.meanRateDiffusion" name="meanRate" mode="mean" internal="true" external="true">
		<treeModel idref="%s_NRR%s.treeModel" />
		<discretizedBranchRates idref="%s_NRR%s.branchRatesDiffusion" />
	</rateStatistic>"""%(pref, nrrnum, pref, nrrnum, pref, nrrnum, pref, nrrnum, pref, nrrnum, pref, nrrnum)
    
    diffdistlparams = diffdistlparams + """
            <parameter idref="%s_NRR%s.branchRatesDiffusion.rates" />"""%(pref, nrrnum)    
    
    traitdatl = traitdatl + """
	<traitDataLikelihood id="%s_NRR%s.traitLikelihood" traitName="loc" scaleByTime="true" forceFullPrecision="false">
			<multivariateDiffusionModel idref="loc.diffusionModel" />
		<treeModel idref="%s_NRR%s.treeModel" />
		<traitParameter>
			<parameter idref="%s_NRR%s.leafTraits" />
		</traitParameter>
		<jitter window="0.5 0.5" duplicatesOnly="false">
			<parameter idref="%s_NRR%s.leafTraits" />
		</jitter>
        <conjugateRootPrior>
            <meanParameter>
                <parameter id="conjugatePriorMean.NRR%s" value="24.499998 101.499998" />
            </meanParameter>
            <priorSampleSize>
                <parameter value="1000000" />
            </priorSampleSize>
        </conjugateRootPrior>
		<arbitraryBranchRates idref="%s_NRR%s.branchRatesDiffusion" />
    </traitDataLikelihood>"""%(pref, nrrnum, pref, nrrnum, pref, nrrnum, pref, nrrnum, nrrnum, pref, nrrnum)
    
    
    vartraits = vartraits + """
	<leafTraitParameter id="MW703458.1.NRR%s.trait" taxon="MW703458.1">
		<treeModel idref="%s_NRR%s.treeModel" />
		<parameter idref="%s_NRR%s.leafTraits" />
	</leafTraitParameter>
	<leafTraitParameter id="OK017803.1.NRR%s.trait" taxon="OK017803.1">
		<treeModel idref="%s_NRR%s.treeModel" />
		<parameter idref="%s_NRR%s.leafTraits" />
	</leafTraitParameter>
	<leafTraitParameter id="OK017805.1.NRR%s.trait" taxon="OK017805.1">
		<treeModel idref="%s_NRR%s.treeModel" />
		<parameter idref="%s_NRR%s.leafTraits" />
	</leafTraitParameter>
	<leafTraitParameter id="OK017806.1.NRR%s.trait" taxon="OK017806.1">
		<treeModel idref="%s_NRR%s.treeModel" />
		<parameter idref="%s_NRR%s.leafTraits" />
	</leafTraitParameter>
    """%(nrrnum, pref, nrrnum, pref, nrrnum,
        nrrnum, pref, nrrnum, pref, nrrnum,
        nrrnum, pref, nrrnum, pref, nrrnum,
        nrrnum, pref, nrrnum, pref, nrrnum)
    
    
    
    spatialpr_rt = spatialpr_rt + """
	<flatGeoSpatialPrior id="sarbeco_root.NRR%s.trait.prior" taxon="root" kmlFileName="C:\\Users\\spyro\\Documents\\kmls_SC2\\Internal_nodes_area.kml" inside="true" union="true" cache="true">
		<data>
			<parameter idref="conjugatePriorMean.NRR%s" />
		</data>
	</flatGeoSpatialPrior>"""%(nrrnum, nrrnum)
    
    spatialpr_var = spatialpr_var + """
	<flatGeoSpatialPrior id="MW703458.1.NRR%s.trait.prior" taxon="MW703458.1" kmlFileName="C:\\Users\\spyro\\Documents\\kmls_SC2\\Yunnan.kml" inside="true" union="true" cache="true">
		<data>
			<parameter idref="MW703458.1.NRR%s.trait" />
		</data>
	</flatGeoSpatialPrior>
	<flatGeoSpatialPrior id="OK017803.1.NRR%s.trait.prior" taxon="OK017803.1" kmlFileName="C:\\Users\\spyro\\Documents\\kmls_SC2\\Hunan.kml" inside="true" union="true" cache="true">
		<data>
			<parameter idref="OK017803.1.NRR%s.trait" />
		</data>
	</flatGeoSpatialPrior>
	<flatGeoSpatialPrior id="OK017805.1.NRR%s.trait.prior" taxon="OK017805.1" kmlFileName="C:\\Users\\spyro\\Documents\\kmls_SC2\\Hunan.kml" inside="true" union="true" cache="true">
		<data>
			<parameter idref="OK017805.1.NRR%s.trait" />
		</data>
	</flatGeoSpatialPrior>
	<flatGeoSpatialPrior id="OK017806.1.NRR%s.trait.prior" taxon="OK017806.1" kmlFileName="C:\\Users\\spyro\\Documents\\kmls_SC2\\Yunnan.kml" inside="true" union="true" cache="true">
		<data>
			<parameter idref="OK017806.1.NRR%s.trait" />
		</data>
	</flatGeoSpatialPrior>"""%(nrrnum, nrrnum, nrrnum, nrrnum, nrrnum, nrrnum, nrrnum, nrrnum,)
    
    
    scaleop = scaleop + """
		<scaleOperator scaleFactor="0.75" weight="0.5">
			<parameter idref="%s_NRR%s.alpha" />
		</scaleOperator>"""%(pref, nrrnum)
    
    
    subtslide = subtslide + """
		<subtreeSlide size="1.0" gaussian="true" weight="30">
			<treeModel idref="%s_NRR%s.treeModel" />
		</subtreeSlide>
		<narrowExchange weight="30">
			<treeModel idref="%s_NRR%s.treeModel" />
		</narrowExchange>
		<wideExchange weight="3">
			<treeModel idref="%s_NRR%s.treeModel" />
		</wideExchange>
		<wilsonBalding weight="3">
			<treeModel idref="%s_NRR%s.treeModel" />
		</wilsonBalding>
		<subtreeLeap size="1.0" weight="30">
			<treeModel idref="%s_NRR%s.treeModel"/>
		</subtreeLeap>
		<fixedHeightSubtreePruneRegraft weight="30">
			<treeModel idref="%s_NRR%s.treeModel"/>
		</fixedHeightSubtreePruneRegraft>
		<scaleOperator scaleFactor="0.75" weight="3">
			<parameter idref="%s_NRR%s.treeModel.rootHeight" />
		</scaleOperator>
		<uniformOperator weight="30">
			<parameter idref="%s_NRR%s.treeModel.internalNodeHeights" />
		</uniformOperator>"""%(pref, nrrnum, pref, nrrnum, pref, nrrnum, pref, nrrnum, pref, nrrnum, pref, nrrnum, pref, nrrnum, pref, nrrnum)
    
    
    hammcop = hammcop + """
		<hamiltonianMonteCarloOperator weight="5" nSteps="5" stepSize="0.1" mode="vanilla" drawVariance="1.0" autoOptimize="true" gradientCheckCount="0">
			<jointGradient>
				<gradient>
					<distributionLikelihood idref="loc.diffusion.prior" />
					<parameter idref="%s_NRR%s.branchRatesDiffusion.rates" />
				</gradient>
				<branchRateGradient id="%s_NRR%s.branchRateGradient" traitName="loc">
					<traitDataLikelihood idref="%s_NRR%s.traitLikelihood" />
				</branchRateGradient>
			</jointGradient>
			<parameter idref="%s_NRR%s.branchRatesDiffusion.rates" />
			<signTransform>
				<parameter idref="%s_NRR%s.branchRatesDiffusion.rates" />
			</signTransform>
		</hamiltonianMonteCarloOperator>"""%(pref, nrrnum, pref, nrrnum, pref, nrrnum, pref, nrrnum, pref, nrrnum)
    
    gibbsop = gibbsop + """
            <wishartStatistics traitName="loc">
                <traitDataLikelihood idref="%s_NRR%s.traitLikelihood" />
            </wishartStatistics>"""%(pref, nrrnum)
        
    geoop = geoop + """
		<uniformGeoSpatialOperator weight="0.5">
			<parameter idref="conjugatePriorMean.NRR%s" />
			<flatGeoSpatialPrior idref="sarbeco_root.NRR%s.trait.prior" />
		</uniformGeoSpatialOperator>"""%(nrrnum, nrrnum)
    
    
    vargeoop = vargeoop + """
		<uniformGeoSpatialOperator weight="0.5">
			<parameter idref="MW703458.1.NRR%s.trait" />
			<flatGeoSpatialPrior idref="MW703458.1.NRR%s.trait.prior" />
		</uniformGeoSpatialOperator>
		<uniformGeoSpatialOperator weight="0.5">
			<parameter idref="OK017803.1.NRR%s.trait" />
			<flatGeoSpatialPrior idref="OK017803.1.NRR%s.trait.prior" />
		</uniformGeoSpatialOperator>
		<uniformGeoSpatialOperator weight="0.5">
			<parameter idref="OK017805.1.NRR%s.trait" />
			<flatGeoSpatialPrior idref="OK017805.1.NRR%s.trait.prior" />
		</uniformGeoSpatialOperator>
		<uniformGeoSpatialOperator weight="0.5">
			<parameter idref="OK017806.1.NRR%s.trait" />
			<flatGeoSpatialPrior idref="OK017806.1.NRR%s.trait.prior" />
		</uniformGeoSpatialOperator>"""%(nrrnum, nrrnum, nrrnum, nrrnum, nrrnum, nrrnum, nrrnum, nrrnum)
    
    
    
    flatgeo_pr = flatgeo_pr + """
					<flatGeoSpatialPrior idref="sarbeco_root.NRR%s.trait.prior" />"""%nrrnum
    
    
    flatgeo_var = flatgeo_var + """
					<flatGeoSpatialPrior idref="MW703458.1.NRR%s.trait"/>
					<flatGeoSpatialPrior idref="OK017803.1.NRR%s.trait"/>
					<flatGeoSpatialPrior idref="OK017805.1.NRR%s.trait"/>
					<flatGeoSpatialPrior idref="OK017806.1.NRR%s.trait"/>
"""%(nrrnum, nrrnum, nrrnum, nrrnum)
    
    
    disc_br = disc_br + """
				<discretizedBranchRates idref="%s_NRR%s.branchRatesDiffusion" />"""%(pref, nrrnum)
    
    tree_like = tree_like + """
				<treeDataLikelihood idref="%s_NRR%s.treeLikelihood" />"""%(pref, nrrnum)
    
    trait_like = trait_like + """
				<traitDataLikelihood idref="%s_NRR%s.traitLikelihood" />"""%(pref, nrrnum)
    
    
    
    logpar = logpar + """
			<parameter idref="%s_NRR%s.treeModel.rootHeight" />"""%(pref, nrrnum)
    
    logtmrca = logtmrca + """
			<tmrcaStatistic idref="%s_NRR%s.age(root)" />
			<tmrcaStatistic idref="%s_NRR%s.age(R637_RacCS203)" />
			<tmrcaStatistic idref="%s_NRR%s.age(R637_BANAL103)" />
			<tmrcaStatistic idref="%s_NRR%s.age(R637_RaTG13)" />
			<tmrcaStatistic idref="%s_NRR%s.age(R637_RpYN06)" />
			<tmrcaStatistic idref="%s_NRR%s.age(R637_Ra22QT77)" />
			<tmrcaStatistic idref="%s_NRR%s.age(R637_BANAL52)" />"""%(pref, nrrnum, pref, nrrnum, pref, nrrnum,
                                                                        pref, nrrnum, pref, nrrnum, pref, nrrnum,
                                                                        pref, nrrnum)
    
    logtreelen = logtreelen + """
			<treeLengthStatistic idref="%s_NRR%s.treeLength" />"""%(pref, nrrnum)
    
    
    logconj = logconj + """
			<parameter idref="conjugatePriorMean.NRR%s" />"""%nrrnum
    
    logratestat = logratestat + """
			<rateStatistic idref="%s_NRR%s.meanRateDiffusion" />"""%(pref, nrrnum)
    
    logtreedat = logtreedat + """
			<treeDataLikelihood idref="%s_NRR%s.treeLikelihood" />"""%(pref, nrrnum)
    
    logtraitdat = logtraitdat + """
			<traitDataLikelihood idref="%s_NRR%s.traitLikelihood" />"""%(pref, nrrnum)
    
    logdisc_br = logdisc_br + """
			<discretizedBranchRates idref="%s_NRR%s.branchRatesDiffusion" />"""%(pref, nrrnum)
    
    logwrite = logwrite + """
		<logTree id="%s_NRR%s.treeFileLog" logEvery="%i" nexusFormat="true" fileName="%s_NRR%s.trees" sortTranslationTable="true">
			<treeModel idref="%s_NRR%s.treeModel" />
			<joint idref="joint" />
			<arbitraryBranchRates idref="%s_NRR%s.branchRatesDiffusion" />
			<multivariateDiffusionModel idref="loc.diffusionModel" />
            <traitDataLikelihood idref="%s_NRR%s.traitLikelihood" />
		</logTree>"""%(pref, nrrnum, logevery, pref, nrrnum, pref, nrrnum, pref, nrrnum, pref, nrrnum)
    
    
    
    
    
    
    seqdic = SeqIO.to_dict(SeqIO.parse(alnf, 'fasta'))
    
    numchars = len(list(seqdic.values())[0].seq)
    
    alns = alns + """   <!-- The sequence alignment (each sequence refers to a taxon above).         -->
    <!-- ntax=%i nchar=%i                                                      -->
    <alignment id="alignment%i" dataType="nucleotide">"""%(taxanum, numchars, i+1)
    
    for i in metadf.index:
        taxid = metadf.loc[i,'name']
        
        alns = alns + """		<sequence>
			<taxon idref="%s"/>
			%s
		</sequence>
"""%(taxid, str(seqdic[taxid].seq).upper())

    alns = alns + """	</alignment>
"""
    


popsize = """	<!-- A prior assumption that the population size has remained constant       -->
	<!-- throughout the time spanned by the genealogy.                           -->
	<constantSize id="constant" units="years">
		<populationSize>
			<parameter id="constant.popSize" value="100.0" lower="0.0" />
		</populationSize>
	</constantSize>
"""


skygrid = """
	<gmrfSkyGridLikelihood id="skygrid">
		<populationSizes>
			<parameter id="skygrid.logPopSize" dimension="50" value="1.0" />
		</populationSizes>
		<precisionParameter>
			<parameter id="skygrid.precision" value="0.1" lower="0.0" />
		</precisionParameter>
		<numGridPoints>
			<parameter id="skygrid.numGridPoints" value="49.0" />
		</numGridPoints>
		<cutOff>
			<parameter id="skygrid.cutOff" value="1000" />
		</cutOff>
		<populationTree>%s
		</populationTree>
	</gmrfSkyGridLikelihood>

	<gmrfSkyrideGradient id="gmrfGradientPop" wrtParameter="logPopulationSizes">
		<gmrfSkyGridLikelihood idref="skygrid" />
	</gmrfSkyrideGradient>
	
	<compoundParameter id="skygrid.parameters">
		<parameter idref="skygrid.precision" />
		<parameter idref="skygrid.logPopSize" />
	</compoundParameter>
=	
	<gmrfSkyrideGradient id="gmrfGradientPrec" wrtParameter="precision">
		<gmrfSkyGridLikelihood idref="skygrid" />
	</gmrfSkyrideGradient>
=	
	<gammaPrior id="skygrid.precision.prior" shape="0.001" scale="1000" offset="0.0">
		<parameter idref="skygrid.precision" />
	</gammaPrior>
	
	<jointGradient id="joint.skygrid.precision">
		<gmrfSkyrideGradient idref="gmrfGradientPrec" />
		<gradient>
			<gammaPrior idref="skygrid.precision.prior" />
			<parameter idref="skygrid.precision" />
		</gradient>
	</jointGradient>
	
	<compoundGradient id="full.skygrid.gradient">
		<jointGradient idref="joint.skygrid.precision" />
		<gmrfSkyrideGradient idref="gmrfGradientPop" />
	</compoundGradient>
"""%skygridpopt    


clockbr = """
	<strictClockBranchRates id="sarbeco.branchRates">
		<rate>
			<parameter id="sarbeco.clock.rate" value="0.0005" lower="0.0"/>
		</rate>
	</strictClockBranchRates>
"""

submod = """
	<HKYModel id="hky">
		<frequencies>
			<frequencyModel dataType="nucleotide">
				<frequencies>
					<parameter id="frequencies" value="0.25 0.25 0.25 0.25" />
				</frequencies>
			</frequencyModel>
		</frequencies>
		<kappa>
			<parameter id="kappa" value="2.0" lower="0.0" />
		</kappa>
	</HKYModel>
"""

comppar = """
	<compoundParameter id="allNus">%s
    </compoundParameter>"""%compparams


distl = """
	<distributionLikelihood id="asrh.hpm">
		<data>%s
		</data>
		<distribution>
			<logNormalDistributionModel id="asrh.model">
				<mu>
					<parameter id="asrh.mean" value="0.0" lower="-Infinity" upper="Infinity" />
				</mu>
				<precision>
					<parameter id="asrh.precision" value="1.0" lower="0.0" upper="Infinity" />
				</precision>
			</logNormalDistributionModel>
		</distribution>
	</distributionLikelihood>
	<normalPrior id="asrh.prior.mean" mean="0.0" stdev="100.0">
		<parameter idref="asrh.mean" />
	</normalPrior>
	<gammaPrior id="asrh.prior.precision" shape="0.001" scale="1000.0" offset="0.0">
		<parameter idref="asrh.precision" />
	</gammaPrior>"""%distlparams


diffmod = """
	<!-- START Multivariate diffusion model                                      -->

	<multivariateDiffusionModel id="loc.diffusionModel">
		<precisionMatrix>
			<matrixParameter id="loc.precision">
				<parameter id="loc.precision.col1" value="0.05 0.002"/>
				<parameter id="loc.precision.col2" value="0.002 0.05"/>
			</matrixParameter>
		</precisionMatrix>
	</multivariateDiffusionModel>

 	<correlation id="loc.correlation" dimension1="1" dimension2="2">
		<matrixParameter idref="loc.precision" />
	</correlation>

	<multivariateWishartPrior id="loc.precisionPrior" df="2">
		<scaleMatrix>
			<matrixParameter>
				<parameter value="1.0 0.0"/>
				<parameter value="0.0 1.0"/>
			</matrixParameter>
		</scaleMatrix>
		<data>
			<parameter idref="loc.precision"/>
		</data>
	</multivariateWishartPrior>
    %s
    
	<distributionLikelihood id="loc.diffusion.prior">
		<data>%s
		</data>
		<distribution>
			<logNormalDistributionModel meanInRealSpace="true">
				<mean>
					<parameter value="1.0" />
				</mean>
				<stdev>
					<parameter id="loc.stdev" value="1.0" lower="0.0" />
				</stdev>
			</logNormalDistributionModel>
		</distribution>
	</distributionLikelihood>
	<!-- END Multivariate diffusion model                                        -->
    """%(diffbr, diffdistlparams)



operators = """
	<!-- Define operators                                                        -->
	<operators id="operators" optimizationSchedule="log">
		<scaleOperator scaleFactor="0.75" weight="1">
			<parameter idref="kappa"/>
		</scaleOperator>
		<deltaExchange delta="0.01" weight="1">
			<parameter idref="frequencies"/>
		</deltaExchange>
		<scaleOperator scaleFactor="0.75" weight="100">
			<parameter idref="sarbeco.clock.rate" />
		</scaleOperator>

		<upDownOperator scaleFactor="0.75" weight="20">
			<up>
				<parameter idref="sarbeco.clock.rate" />
			</up>
			<down>
				<parameter idref="skygrid.logPopSize" />
			</down>
		</upDownOperator>


		<deltaExchange delta="0.01" weight="5">
			<parameter idref="allNus" />
		</deltaExchange>%s
        
		<normalNormalMeanGibbsOperator weight="2.0">
			<likelihood>
				<distribution idref="asrh.hpm" />
			</likelihood>
			<prior>
				<normalPrior idref="asrh.prior.mean" />
			</prior>
		</normalNormalMeanGibbsOperator>
		<normalGammaPrecisionGibbsOperator weight="2.0">
			<likelihood>
				<distribution idref="asrh.hpm" />
			</likelihood>
			<prior>
				<gammaPrior idref="asrh.prior.precision" />
			</prior>
		</normalGammaPrecisionGibbsOperator>%s
        
		<gmrfGridBlockUpdateOperator scaleFactor="1.0" weight="0.1">
			<gmrfSkyrideLikelihood idref="skygrid" />
		</gmrfGridBlockUpdateOperator>
		<scaleOperator scaleFactor="0.75" weight="0.1">
			<parameter idref="skygrid.precision" />
		</scaleOperator>
		<hamiltonianMonteCarloOperator weight="20" nSteps="50" stepSize="1E-2" mode="vanilla" autoOptimize="true" gradientCheckCount="0" gradientCheckTolerance="1E-1" preconditioning="diagonal" preconditioningUpdateFrequency="100">
	 		<compoundGradient idref="full.skygrid.gradient" />
			<compoundParameter idref="skygrid.parameters" />
			<signTransform start="1" end="1">
				<compoundParameter idref="skygrid.parameters" />
			</signTransform>
		</hamiltonianMonteCarloOperator>
		
		<scaleOperator scaleFactor="0.75" weight="30">
			<parameter idref="loc.stdev" />
		</scaleOperator>%s
        
		<precisionGibbsOperator weight="10">%s
            <multivariateWishartPrior idref="loc.precisionPrior" />
		</precisionGibbsOperator>%s
        
        %s
        
	</operators>
"""%(scaleop, subtslide, hammcop, gibbsop, geoop, vargeoop)



mcmc = """
	<!-- Define MCMC                                                             -->
	<mcmc id="mcmc" chainLength="%i" autoOptimize="true" operatorAnalysis="NRR1.ops">
		<joint id="joint">
			<prior id="prior">
				<logNormalPrior mu="1.0" sigma="1.25" offset="0.0">
					<parameter idref="kappa"/>
				</logNormalPrior>
				<dirichletPrior alpha="1.0" sumsTo="1.0">
					<parameter idref="frequencies"/>
				</dirichletPrior>

				<dirichletPrior alpha="1.0" sumsTo="1.0">
					<parameter idref="allNus" />
				</dirichletPrior>

				<distributionLikelihood idref="asrh.hpm" />
				<normalPrior idref="asrh.prior.mean" />
				<gammaPrior idref="asrh.prior.precision" />

				<normalPrior mean="0.0006" stdev="0.0000245">
					<parameter idref="sarbeco.clock.rate" />
				</normalPrior>

				<gammaPrior shape="0.001" scale="1000.0" offset="0.0">
					<parameter idref="skygrid.precision" />
				</gammaPrior>
				<gmrfSkyGridLikelihood idref="skygrid" />

				
				<exponentialPrior mean="0.3333333333333333" offset="0.0">
					<parameter idref="loc.stdev" />
				</exponentialPrior>
				
				<distributionLikelihood idref="loc.diffusion.prior" />
				<multivariateWishartPrior idref="loc.precisionPrior" />
				
				<geoDistributionCollection id="allGeoDistributions">
                %s
                %s
				</geoDistributionCollection>

				<strictClockBranchRates idref="sarbeco.branchRates" />
                %s
			</prior>
            
			<likelihood id="likelihood">%s
                
				<!-- START Multivariate diffusion model                                      -->%s
                
				<!-- END Multivariate diffusion model                                        -->

			</likelihood>
		</joint>
		<operators idref="operators"/>
        
		<!-- write log to screen                                                     -->
		<log id="screenLog" logEvery="%i">
			<column label="Joint" dp="4" width="12">
				<joint idref="joint"/>
			</column>
			<column label="Prior" dp="4" width="12">
				<prior idref="prior"/>
			</column>
			<column label="Likelihood" dp="4" width="12">
				<likelihood idref="likelihood"/>
			</column>
		</log>

		<!-- write log to file                                                       -->
		<log id="fileLog" logEvery="%i" fileName="%s.log" overwrite="false">
			<joint idref="joint"/>
			<prior idref="prior"/>
			<likelihood idref="likelihood"/>
            %s
            %s
            %s
            
			<parameter idref="skygrid.precision" />
			<parameter idref="skygrid.logPopSize" />
			<parameter idref="skygrid.cutOff" />
			<parameter idref="kappa" />
			<parameter idref="frequencies" />
			<parameter idref="sarbeco.clock.rate" />
			<parameter idref="allNus" />

			<matrixParameter idref="loc.precision" />
			<correlation idref="loc.correlation" />
			
			<parameter idref="loc.stdev" />
            %s
            %s
            %s
            %s
            %s
            
			<gmrfSkyGridLikelihood idref="skygrid" />
		</log>

		<!-- write tree log to file                                                  -->%s
	</mcmc>
	
	<report>
		<property name="timer">
			<mcmc idref="mcmc"/>
		</property>
	</report>
	
</beast>        
"""%(chainlen,
    flatgeo_pr, 
    flatgeo_var, 
    disc_br, 
    tree_like, 
    trait_like,
    logevery/5,
    logevery,
    outnam,
    logpar,
    logtmrca,
    logtreelen,
    logconj,
    logratestat, 
    logtreedat,
    logtraitdat,
    logdisc_br,
    logwrite)


#SKIPPED: 		<log id="fileLog.traits" logEvery="500000" fileName="SC2.tips.log" overwrite="false">


allxml = '\n'.join([header, 
                    taxa, 
                    alns, 
                    pats, 
                    popsize, 
                    startt, 
                    tmod, 
                    tmrca,
                    tmrca_custtaxa,
                    tlen, 
                    skygrid, 
                    clockbr, 
                    submod,
                    sitemod, 
                    treedatl, 
                    comppar,
                    distl, 
                    diffmod, 
                    traitdatl, 
                    vartraits,
                    spatialpr_rt, 
                    spatialpr_var,
                    operators,
                    mcmc])


with open('%s.xml'%outnam, 'w') as out:
    out.write(allxml)